# Generated by Django 6.0.6 on 2026-07-02 10:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Asl URL')),
                ('short_code', models.SlugField(blank=True, max_length=15, unique=True, verbose_name='Qisqa kod')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Bosishlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Qisqa havola',
                'verbose_name_plural': 'Qisqa havolalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
