# Generated by Django 6.0.6 on 2026-07-02 10:53

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti')),
                ('referrer', models.CharField(blank=True, max_length=2000, verbose_name='Manba (referrer)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('browser', models.CharField(default='Boshqa', max_length=32, verbose_name='Brauzer')),
                ('device', models.CharField(default='Kompyuter', max_length=32, verbose_name='Qurilma')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='main.shorturl', verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Bosish',
                'verbose_name_plural': 'Bosishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
